on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "test-action"
      - name: Test CDK Diff
        id: diff
        uses:  jesse-peters/test-action@main
      - name: Get the diff
        run: echo "The diff was ${{ steps.diff.outputs.diff }}"